namespace SearchSprint.Indexer;

internal static class SeedData
{
    internal static readonly List<Movie> Movies =
    [
        new() { Id = 1,  Title = "The Godfather",             Genres = ["Crime", "Drama"],                    Rating = 9.2f, ReleaseDate = new DateTime(1972, 3,  24), Overview = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son." },
        new() { Id = 2,  Title = "Goodfellas",                Genres = ["Crime", "Biography", "Drama"],       Rating = 8.7f, ReleaseDate = new DateTime(1990, 9,  19), Overview = "The story of Henry Hill and his life in the mob, covering his rise through the ranks and his eventual fall." },
        new() { Id = 3,  Title = "Interstellar",              Genres = ["Sci-Fi", "Drama"],                   Rating = 8.6f, ReleaseDate = new DateTime(2014, 11,  7), Overview = "A team of astronauts travel through a wormhole near Saturn in search of a new home for humanity as Earth faces ecological collapse." },
        new() { Id = 4,  Title = "The Dark Knight",           Genres = ["Action", "Crime", "Drama"],          Rating = 9.0f, ReleaseDate = new DateTime(2008, 7,  18), Overview = "Batman raises the stakes in his war on crime, facing the Joker, a criminal mastermind who wants to plunge Gotham into anarchy." },
        new() { Id = 5,  Title = "Schindler's List",          Genres = ["Biography", "Drama", "History"],     Rating = 9.0f, ReleaseDate = new DateTime(1993, 12, 15), Overview = "In German-occupied Poland, industrialist Oskar Schindler saves the lives of more than a thousand Jewish refugees during the Holocaust." },
        new() { Id = 6,  Title = "Forrest Gump",              Genres = ["Drama", "Romance"],                  Rating = 8.8f, ReleaseDate = new DateTime(1994, 7,   6), Overview = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with a low IQ." },
        new() { Id = 7,  Title = "Inception",                 Genres = ["Action", "Sci-Fi", "Thriller"],     Rating = 8.8f, ReleaseDate = new DateTime(2010, 7,  16), Overview = "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a target's subconscious." },
        new() { Id = 8,  Title = "The Matrix",                Genres = ["Action", "Sci-Fi"],                  Rating = 8.7f, ReleaseDate = new DateTime(1999, 3,  31), Overview = "A computer hacker learns that the world he lives in is a simulated reality controlled by machines, and joins a rebellion to overthrow them." },
        new() { Id = 9,  Title = "Parasite",                  Genres = ["Comedy", "Drama", "Thriller"],       Rating = 8.5f, ReleaseDate = new DateTime(2019, 5,  30), Overview = "A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals." },
        new() { Id = 10, Title = "Spirited Away",             Genres = ["Animation", "Adventure", "Family"],  Rating = 8.6f, ReleaseDate = new DateTime(2001, 7,  20), Overview = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods and witches and must find a way to free her parents." },
        new() { Id = 11, Title = "The Silence of the Lambs",  Genres = ["Crime", "Drama", "Thriller"],        Rating = 8.6f, ReleaseDate = new DateTime(1991, 2,  14), Overview = "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer who skins his victims." },
        new() { Id = 12, Title = "Titanic",                   Genres = ["Drama", "Romance"],                  Rating = 7.9f, ReleaseDate = new DateTime(1997, 12, 19), Overview = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the ill-fated R.M.S. Titanic." },
        new() { Id = 13, Title = "Avengers: Endgame",         Genres = ["Action", "Adventure", "Sci-Fi"],    Rating = 8.4f, ReleaseDate = new DateTime(2019, 4,  26), Overview = "After Thanos wipes out half of all life in the universe, the surviving Avengers assemble for one final stand to undo his actions and restore order." },
        new() { Id = 14, Title = "The Shawshank Redemption",  Genres = ["Drama"],                             Rating = 9.3f, ReleaseDate = new DateTime(1994, 9,  23), Overview = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency." },
        new() { Id = 15, Title = "Get Out",                   Genres = ["Horror", "Mystery", "Thriller"],    Rating = 7.7f, ReleaseDate = new DateTime(2017, 2,  24), Overview = "A young Black man visits his white girlfriend's family estate, where he uncovers a disturbing secret about the enclave of residents." },
        new() { Id = 16, Title = "Pulp Fiction",              Genres = ["Crime", "Drama"],                    Rating = 8.9f, ReleaseDate = new DateTime(1994, 10, 14), Overview = "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption in Los Angeles." },
        new() { Id = 17, Title = "The Lion King",             Genres = ["Animation", "Adventure", "Drama"],   Rating = 8.5f, ReleaseDate = new DateTime(1994, 6,  24), Overview = "A young lion prince flees his kingdom after his uncle frames him for his father's murder, only to return years later to reclaim his throne." },
        new() { Id = 18, Title = "Gladiator",                 Genres = ["Action", "Adventure", "Drama"],     Rating = 8.5f, ReleaseDate = new DateTime(2000, 5,   5), Overview = "A former Roman general is betrayed by the emperor's corrupt son and sold into slavery, rising as a gladiator to seek vengeance." },
        new() { Id = 19, Title = "Eternal Sunshine of the Spotless Mind", Genres = ["Drama", "Romance", "Sci-Fi"], Rating = 8.3f, ReleaseDate = new DateTime(2004, 3, 19), Overview = "After a painful breakup, a couple undergoes a medical procedure to erase memories of each other, only to fall in love again during the process." },
        new() { Id = 20, Title = "No Country for Old Men",    Genres = ["Crime", "Drama", "Thriller"],        Rating = 8.1f, ReleaseDate = new DateTime(2007, 11,  9), Overview = "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and finds two million dollars and a mysterious case near the Rio Grande." },
    ];
}
